/**
This file was edited by Shankar using VS code on 17th Jan 2026
******************************************************************************
 * @file        Dcm_DIDHandlers.c
 * @brief       DCM ReadDataByIdentifier / WriteDataByIdentifier Callback
 *              Implementations — Powertrain / EMS ECU
 *
 * @details     Implements all DID data handler callbacks registered in the
 *              DCM AUTOSAR configuration (DaVinci Configurator Pro / Vector
 *              MICROSAR). Called by DCM BSW when UDS service 0x22
 *              (ReadDataByIdentifier) or 0x2E (WriteDataByIdentifier)
 *              is received from a diagnostic tester.
 *
 *              Architecture:
 *              ┌──────────┐   UDS 0x22/0x2E   ┌──────────────────┐
 *              │  Tester  │ ─────────────────► │   DCM BSW        │
 *              └──────────┘                    │  (MICROSAR)      │
 *                                              └────────┬─────────┘
 *                                                       │ DcmDspDidDataReadFnc
 *                                                       │ DcmDspDidDataWriteFnc
 *                                              ┌────────▼─────────┐
 *                                              │ Dcm_DIDHandlers  │  ◄─ THIS FILE
 *                                              └────────┬─────────┘
 *                                    ┌──────────────────┼──────────────┐
 *                               Rte_Read()          NvM_ReadBlock()  Rte_Read()
 *                            ┌────────▼──┐        ┌────────▼──┐  ┌───▼──────┐
 *                            │ App SWCs  │        │   NvM     │  │ IoHwAb   │
 *                            └───────────┘        └───────────┘  └──────────┘
 *
 *              Signal encoding follows AUTOSAR/OEM conventions:
 *                - Big-endian byte order for multi-byte values
 *                - Physical = Raw × Resolution + Offset (where applicable)
 *                - Raw values stored MSB first in Data[] buffer
 *
 * @version     1.0.0
 * @date        2026-05-03
 *
 * @note        MISRA C:2012 Rule 15.5 — single point of exit preferred.
 *              NULL pointer checks on Data parameter per AUTOSAR SWS_Dcm.
 *              Rte_Read / NvM calls shown as representative — actual port
 *              names are generated by DaVinci Developer from SWC ARXML.
 ******************************************************************************
 */

/*============================================================================
  INCLUDES
============================================================================*/
#include "Dcm_DIDHandlers.h"
#include "Rte_DcmDIDHandlers.h"     /* RTE-generated: Rte_Read_*, Rte_Write_* */
#include "NvM.h"                     /* NvM_ReadBlock, NvM_WriteBlock           */
#include "Dcm.h"                     /* Dcm_GetSesCtrlType                      */
#include "Det.h"                     /* Development error reporting             */
#include "string.h"                  /* memcpy, memset                          */

/*============================================================================
  VERSION INFORMATION — stored in flash, sourced by F180/F181/F182/F189/F195
  Project shall replace these with build-system generated values.
============================================================================*/

/** @brief Boot software identification string (16 bytes) */
static const uint8 Dcm_BootSwIdent[DCM_DID_LEN_F180] =
{
    /* Example: "BOOT_EMS1_V1.00 " */
    0x42U, 0x4FU, 0x4FU, 0x54U, 0x5FU, 0x45U, 0x4DU, 0x53U,
    0x31U, 0x5FU, 0x56U, 0x31U, 0x2EU, 0x30U, 0x30U, 0x20U
};

/** @brief Application software identification string (16 bytes) */
static const uint8 Dcm_AppSwIdent[DCM_DID_LEN_F181] =
{
    /* Example: "APPL_EMS1_V1.00 " */
    0x41U, 0x50U, 0x50U, 0x4CU, 0x5FU, 0x45U, 0x4DU, 0x53U,
    0x31U, 0x5FU, 0x56U, 0x31U, 0x2EU, 0x30U, 0x30U, 0x20U
};

/** @brief Application data (calibration) identification string (16 bytes) */
static const uint8 Dcm_AppDataIdent[DCM_DID_LEN_F182] =
{
    /* Example: "CAL__EMS1_V1.00 " */
    0x43U, 0x41U, 0x4CU, 0x5FU, 0x5FU, 0x45U, 0x4DU, 0x53U,
    0x31U, 0x5FU, 0x56U, 0x31U, 0x2EU, 0x30U, 0x30U, 0x20U
};

/** @brief ECU Hardware Number — OEM part number, 11 bytes ASCII */
static const uint8 Dcm_EcuHwNumber[DCM_DID_LEN_F191] =
{
    /* Example: "HW12345678A" */
    0x48U, 0x57U, 0x31U, 0x32U, 0x33U, 0x34U, 0x35U,
    0x36U, 0x37U, 0x38U, 0x41U
};

/** @brief Supplier ECU Hardware Number, 11 bytes */
static const uint8 Dcm_SupplierHwNumber[DCM_DID_LEN_F192] =
{
    0x53U, 0x48U, 0x57U, 0x31U, 0x32U, 0x33U, 0x34U,
    0x35U, 0x36U, 0x37U, 0x38U
};

/** @brief Supplier ECU HW Version, 2 bytes: Major, Minor */
static const uint8 Dcm_SupplierHwVersion[DCM_DID_LEN_F193] = { 0x01U, 0x00U };

/** @brief Supplier ECU SW Number, 11 bytes */
static const uint8 Dcm_SupplierSwNumber[DCM_DID_LEN_F194] =
{
    0x53U, 0x53U, 0x57U, 0x31U, 0x32U, 0x33U, 0x34U,
    0x35U, 0x36U, 0x37U, 0x38U
};

/** @brief Supplier ECU SW Version, 4 bytes: Major, Minor, Patch, Build */
static const uint8 Dcm_SupplierSwVersion[DCM_DID_LEN_F195] =
    { 0x01U, 0x00U, 0x00U, 0x00U };

/** @brief ECU SW Number (OEM), 11 bytes */
static const uint8 Dcm_EcuSwNumber[DCM_DID_LEN_F188] =
{
    0x45U, 0x53U, 0x57U, 0x31U, 0x32U, 0x33U, 0x34U,
    0x35U, 0x36U, 0x37U, 0x38U
};

/** @brief ECU SW Version, 4 bytes: Major, Minor, Patch, Build */
static const uint8 Dcm_EcuSwVersion[DCM_DID_LEN_F189] =
    { 0x01U, 0x00U, 0x00U, 0x00U };

/** @brief System Supplier ID — 3 bytes CAGE code */
static const uint8 Dcm_SupplierID[DCM_DID_LEN_F18A] = { 0x53U, 0x55U, 0x50U };

/** @brief System Name / Engine Type — 4 bytes ASCII e.g. "EMS1" */
static const uint8 Dcm_SystemName[DCM_DID_LEN_F197] =
    { 0x45U, 0x4DU, 0x53U, 0x31U };

/** @brief Supported Functional Units bitmask — 4 bytes */
static const uint8 Dcm_SupportedFuncUnits[DCM_DID_LEN_F18E] =
    { 0x00U, 0x00U, 0x03U, 0xFFU };

/** @brief Calibration dataset version — 4 bytes Major.Minor.Patch.Rev */
static const uint8 Dcm_CalDatasetVersion[DCM_DID_LEN_F1A0] =
    { 0x01U, 0x00U, 0x00U, 0x00U };

/** @brief Spare Part Number — 13 bytes OEM-assigned */
static const uint8 Dcm_SparePartNumber[DCM_DID_LEN_F187] =
{
    0x30U, 0x31U, 0x32U, 0x33U, 0x34U, 0x35U, 0x36U,
    0x37U, 0x38U, 0x39U, 0x41U, 0x42U, 0x43U
};

/*============================================================================
  NvM BLOCK HANDLES — project assigns actual IDs in NvM configuration
  These are placeholder declarations; actual values from NvM_Cfg.h
============================================================================*/
extern const uint8 NvM_VIN_Block[];            /* NvM block: VIN (17 bytes)  */
extern const uint8 NvM_EcuSerial_Block[];      /* NvM block: Serial (10 bytes)*/
extern const uint8 NvM_BootSwFp_Block[];       /* NvM block: Boot fingerprint */
extern const uint8 NvM_AppSwFp_Block[];        /* NvM block: App SW fingerprint*/
extern const uint8 NvM_AppDataFp_Block[];      /* NvM block: App data fingerprint*/
extern const uint8 NvM_MfgDate_Block[];        /* NvM block: Manufacturing date*/
extern const uint8 NvM_ProgDate_Block[];       /* NvM block: Programming date  */
extern const uint8 NvM_ResetCounter_Block[];   /* NvM block: Reset counter     */
extern const uint8 NvM_ResetCause_Block[];     /* NvM block: Reset cause       */
extern const uint8 NvM_NvmWriteCounter_Block[];/* NvM block: NvM write counter */

/* NvM Block IDs — replace with actual IDs from NvM_Cfg.h */
#define DCM_NVM_BLOCK_VIN               (2U)
#define DCM_NVM_BLOCK_ECU_SERIAL        (3U)
#define DCM_NVM_BLOCK_BOOT_SW_FP        (4U)
#define DCM_NVM_BLOCK_APP_SW_FP         (5U)
#define DCM_NVM_BLOCK_APP_DATA_FP       (6U)
#define DCM_NVM_BLOCK_MFG_DATE          (7U)
#define DCM_NVM_BLOCK_PROG_DATE         (8U)
#define DCM_NVM_BLOCK_RESET_COUNTER     (9U)
#define DCM_NVM_BLOCK_RESET_CAUSE       (10U)
#define DCM_NVM_BLOCK_NVM_WRITE_CTR     (11U)

/*============================================================================
  LOCAL RAM BUFFERS — mirrors of NvM blocks used for DID read/write
  Actual buffers generated by NvM tooling; declared here for reference.
============================================================================*/
static uint8 Dcm_VinBuffer[DCM_DID_LEN_F190];
static uint8 Dcm_EcuSerialBuffer[DCM_DID_LEN_F18C];
static uint8 Dcm_BootSwFpBuffer[DCM_DID_LEN_F183];
static uint8 Dcm_AppSwFpBuffer[DCM_DID_LEN_F184];
static uint8 Dcm_AppDataFpBuffer[DCM_DID_LEN_F185];
static uint8 Dcm_MfgDateBuffer[DCM_DID_LEN_F18B];
static uint8 Dcm_ProgDateBuffer[DCM_DID_LEN_F1A2];
static uint8 Dcm_ResetCounterBuffer[DCM_DID_LEN_D003];
static uint8 Dcm_ResetCauseBuffer[DCM_DID_LEN_D004];
static uint8 Dcm_NvmWriteCtrBuffer[DCM_DID_LEN_D005];

/*============================================================================
  LOCAL HELPER MACROS
============================================================================*/

/**
 * @brief   Write a uint16 value MSB-first into a byte buffer at offset.
 * @param   buf     Pointer to destination byte buffer
 * @param   offset  Byte offset in buffer
 * @param   val     uint16 value to encode
 */
#define DCM_WRITE_UINT16_BE(buf, offset, val)                   \
    do {                                                        \
        (buf)[(offset)]     = (uint8)(((val) >> 8U) & 0xFFU);  \
        (buf)[(offset) + 1U] = (uint8)((val) & 0xFFU);         \
    } while (0)

/**
 * @brief   Write a uint32 value MSB-first into a byte buffer at offset.
 */
#define DCM_WRITE_UINT32_BE(buf, offset, val)                           \
    do {                                                                \
        (buf)[(offset)]      = (uint8)(((val) >> 24U) & 0xFFU);        \
        (buf)[(offset) + 1U] = (uint8)(((val) >> 16U) & 0xFFU);        \
        (buf)[(offset) + 2U] = (uint8)(((val) >>  8U) & 0xFFU);        \
        (buf)[(offset) + 3U] = (uint8)((val) & 0xFFU);                 \
    } while (0)

/**
 * @brief   NULL pointer guard — returns E_NOT_OK if ptr is NULL.
 *          Used at function entry per AUTOSAR defensive programming.
 */
#define DCM_RETURN_IF_NULL(ptr)                                         \
    do {                                                                \
        if ((ptr) == NULL_PTR) {                                        \
            Det_ReportError(DCM_MODULE_ID, 0U,                         \
                            DCM_E_PARAM_POINTER, DCM_E_PARAM_POINTER); \
            return E_NOT_OK;                                            \
        }                                                               \
    } while (0)

/*============================================================================
  SECTION 1 — IDENTIFICATION DIDs (0xFxxx) READ HANDLERS
  These are synchronous reads (USE_DATA_SYNCH_FNC) unless marked async.
  Async reads (USE_DATA_ASYNCH_FNC) read from NvM RAM mirror.
============================================================================*/

/**
 * @brief   DID 0xF186 — Active Diagnostic Session
 * @details Returns the currently active DCM session type.
 *          1 byte: 0x01=Default, 0x02=Programming, 0x03=Extended.
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK on success, E_NOT_OK on failure
 */
Std_ReturnType Dcm_ReadData_F186(uint8 *Data)
{
    Dcm_SesCtrlType currentSession;
    Std_ReturnType  retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Dcm_GetSesCtrlType(&currentSession);

    if (retVal == E_OK)
    {
        Data[0] = (uint8)currentSession;
    }
    else
    {
        Data[0] = (uint8)DCM_DEFAULT_SESSION;
        retVal  = E_NOT_OK;
    }

    return retVal;
}

/**
 * @brief   DID 0xF190 — Vehicle Identification Number (VIN)
 * @details Reads 17-byte ASCII VIN from NvM RAM mirror.
 *          Async read: NvM block pre-loaded at startup by NvM_ReadAll().
 * @param   Data    [out] 17-byte response buffer
 * @return  E_OK on success
 */
Std_ReturnType Dcm_ReadData_F190(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_VinBuffer, DCM_DID_LEN_F190);
    return E_OK;
}

/**
 * @brief   DID 0xF18C — ECU Serial Number
 * @details Reads 10-byte ECU serial number from NvM (written at EOL).
 * @param   Data    [out] 10-byte response buffer
 * @return  E_OK on success
 */
Std_ReturnType Dcm_ReadData_F18C(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_EcuSerialBuffer, DCM_DID_LEN_F18C);
    return E_OK;
}

/**
 * @brief   DID 0xF180 — Boot Software Identification
 * @details Reads 16-byte boot SW identification from const flash symbol.
 * @param   Data    [out] 16-byte response buffer
 * @return  E_OK always (const data)
 */
Std_ReturnType Dcm_ReadData_F180(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_BootSwIdent, DCM_DID_LEN_F180);
    return E_OK;
}

/**
 * @brief   DID 0xF181 — Application Software Identification
 * @param   Data    [out] 16-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F181(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_AppSwIdent, DCM_DID_LEN_F181);
    return E_OK;
}

/**
 * @brief   DID 0xF182 — Application Data Identification
 * @param   Data    [out] 16-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F182(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_AppDataIdent, DCM_DID_LEN_F182);
    return E_OK;
}

/**
 * @brief   DID 0xF183 — Boot Software Fingerprint
 * @details 10 bytes: [3 bytes date BCD YYYYMMDD] + [7 bytes tester ID].
 *          Read from NvM — written by bootloader post-programming.
 * @param   Data    [out] 10-byte response buffer
 * @return  E_OK on success
 */
Std_ReturnType Dcm_ReadData_F183(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_BootSwFpBuffer, DCM_DID_LEN_F183);
    return E_OK;
}

/**
 * @brief   DID 0xF184 — Application Software Fingerprint
 * @param   Data    [out] 10-byte response buffer
 * @return  E_OK
 */
Std_ReturnType Dcm_ReadData_F184(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_AppSwFpBuffer, DCM_DID_LEN_F184);
    return E_OK;
}

/**
 * @brief   DID 0xF185 — Application Data Fingerprint
 * @param   Data    [out] 10-byte response buffer
 * @return  E_OK
 */
Std_ReturnType Dcm_ReadData_F185(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_AppDataFpBuffer, DCM_DID_LEN_F185);
    return E_OK;
}

/**
 * @brief   DID 0xF187 — Vehicle Manufacturer Spare Part Number
 * @param   Data    [out] 13-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F187(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SparePartNumber, DCM_DID_LEN_F187);
    return E_OK;
}

/**
 * @brief   DID 0xF188 — Vehicle Manufacturer ECU Software Number
 * @param   Data    [out] 11-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F188(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_EcuSwNumber, DCM_DID_LEN_F188);
    return E_OK;
}

/**
 * @brief   DID 0xF189 — Vehicle Manufacturer ECU Software Version
 * @details 4 bytes: Major, Minor, Patch, Build.
 * @param   Data    [out] 4-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F189(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_EcuSwVersion, DCM_DID_LEN_F189);
    return E_OK;
}

/**
 * @brief   DID 0xF18A — System Supplier Identifier
 * @details 3 bytes CAGE code.
 * @param   Data    [out] 3-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F18A(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SupplierID, DCM_DID_LEN_F18A);
    return E_OK;
}

/**
 * @brief   DID 0xF18B — ECU Manufacturing Date
 * @details 3 bytes BCD: [Year offset from 2000][Month][Day].
 *          Example: 2026-05-03 → {0x26, 0x05, 0x03}.
 * @param   Data    [out] 3-byte response buffer
 * @return  E_OK
 */
Std_ReturnType Dcm_ReadData_F18B(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_MfgDateBuffer, DCM_DID_LEN_F18B);
    return E_OK;
}

/**
 * @brief   DID 0xF18E — Supported Functional Units
 * @details 4-byte bitmask representing supported diagnostic service groups.
 * @param   Data    [out] 4-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F18E(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SupportedFuncUnits, DCM_DID_LEN_F18E);
    return E_OK;
}

/**
 * @brief   DID 0xF191 — Vehicle Manufacturer ECU Hardware Number
 * @param   Data    [out] 11-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F191(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_EcuHwNumber, DCM_DID_LEN_F191);
    return E_OK;
}

/**
 * @brief   DID 0xF192 — System Supplier ECU Hardware Number
 * @param   Data    [out] 11-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F192(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SupplierHwNumber, DCM_DID_LEN_F192);
    return E_OK;
}

/**
 * @brief   DID 0xF193 — System Supplier ECU Hardware Version
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F193(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SupplierHwVersion, DCM_DID_LEN_F193);
    return E_OK;
}

/**
 * @brief   DID 0xF194 — System Supplier ECU Software Number
 * @param   Data    [out] 11-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F194(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SupplierSwNumber, DCM_DID_LEN_F194);
    return E_OK;
}

/**
 * @brief   DID 0xF195 — System Supplier ECU Software Version
 * @param   Data    [out] 4-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F195(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SupplierSwVersion, DCM_DID_LEN_F195);
    return E_OK;
}

/**
 * @brief   DID 0xF197 — System Name / Engine Type
 * @details 4 bytes ASCII. Example: "EMS1" = {0x45,0x4D,0x53,0x31}.
 * @param   Data    [out] 4-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F197(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_SystemName, DCM_DID_LEN_F197);
    return E_OK;
}

/**
 * @brief   DID 0xF1A0 — Calibration/Parameter Data Set Version
 * @details 4 bytes: Major, Minor, Patch, Revision.
 * @param   Data    [out] 4-byte response buffer
 * @return  E_OK always
 */
Std_ReturnType Dcm_ReadData_F1A0(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_CalDatasetVersion, DCM_DID_LEN_F1A0);
    return E_OK;
}

/**
 * @brief   DID 0xF1A2 — ECU Programming Date
 * @details 3 bytes BCD: [Year][Month][Day].
 *          Written by bootloader at end of programming sequence.
 * @param   Data    [out] 3-byte response buffer
 * @return  E_OK
 */
Std_ReturnType Dcm_ReadData_F1A2(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    (void)memcpy(Data, Dcm_ProgDateBuffer, DCM_DID_LEN_F1A2);
    return E_OK;
}

/*============================================================================
  SECTION 2 — POWERTRAIN LIVE DATA DIDs (0x2xxx) READ HANDLERS
  All synchronous (USE_DATA_SYNCH_FNC). Sourced via Rte_Read from
  application SWC ports. Encoding applied before placing into Data buffer.
============================================================================*/

/**
 * @brief   DID 0x2001 — Engine RPM
 * @details 2 bytes uint16, MSB first.
 *          Physical value [rpm] = Raw × 0.25
 *          Raw = Physical / 0.25 = Physical × 4
 *          Range: 0–16383.75 rpm. Raw range: 0x0000–0xFFFF.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2001(uint8 *Data)
{
    uint16         engSpeedRpm;   /* Physical value in rpm × 4 (raw) */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_EngSpeed_val(&engSpeedRpm);

    if (retVal == E_OK)
    {
        /* Raw = Physical_rpm × 4 (resolution 0.25 rpm/bit) */
        DCM_WRITE_UINT16_BE(Data, 0U, engSpeedRpm);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU); /* invalid marker */
    }

    return retVal;
}

/**
 * @brief   DID 0x2002 — Engine Coolant Temperature
 * @details 1 byte uint8.
 *          Physical [°C] = Raw - 40
 *          Raw = Physical + 40. Range: -40°C (0x00) to +215°C (0xFF).
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2002(uint8 *Data)
{
    sint16         coolantTemp_degC;
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_CoolantTemp_val(&coolantTemp_degC);

    if (retVal == E_OK)
    {
        sint16 rawVal = coolantTemp_degC + 40;

        if (rawVal < 0)       { rawVal = 0; }
        if (rawVal > 255)     { rawVal = 255; }

        Data[0] = (uint8)rawVal;
    }
    else
    {
        Data[0] = 0xFFU; /* invalid marker */
    }

    return retVal;
}

/**
 * @brief   DID 0x2003 — Intake Air Temperature
 * @details 1 byte. Physical [°C] = Raw - 40. Same encoding as 0x2002.
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2003(uint8 *Data)
{
    sint16         iatTemp_degC;
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_IntakeAirTemp_val(&iatTemp_degC);

    if (retVal == E_OK)
    {
        sint16 rawVal = iatTemp_degC + 40;

        if (rawVal < 0)   { rawVal = 0; }
        if (rawVal > 255) { rawVal = 255; }

        Data[0] = (uint8)rawVal;
    }
    else
    {
        Data[0] = 0xFFU;
    }

    return retVal;
}

/**
 * @brief   DID 0x2004 — Throttle Position
 * @details 1 byte. Physical [%] = Raw × 0.4 → Raw = Physical / 0.4 = Physical × 2.5
 *          Range: 0% (0x00) to ~100% (0xFA=250 → 100%).
 *          Encode: Raw = (uint8)(Physical_percent * 2.5f)
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2004(uint8 *Data)
{
    uint8          throttlePercent; /* 0–100 physical percent */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_ThrottlePos_val(&throttlePercent);

    if (retVal == E_OK)
    {
        /* Raw = Physical × 2.5, capped at 0xFF */
        uint16 rawVal = ((uint16)throttlePercent * 5U) / 2U;
        Data[0] = (rawVal > 0xFFU) ? 0xFFU : (uint8)rawVal;
    }
    else
    {
        Data[0] = 0xFFU;
    }

    return retVal;
}

/**
 * @brief   DID 0x2005 — Manifold Absolute Pressure
 * @details 2 bytes uint16 MSB first.
 *          Physical [kPa] = Raw × 0.1 → Raw = Physical_kPa × 10
 *          Range: 0–655.35 kPa.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2005(uint8 *Data)
{
    uint16         mapKPa_x10;   /* MAP in units of 0.1 kPa (raw) */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_MAP_val(&mapKPa_x10);

    if (retVal == E_OK)
    {
        DCM_WRITE_UINT16_BE(Data, 0U, mapKPa_x10);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU);
    }

    return retVal;
}

/**
 * @brief   DID 0x2006 — Battery Voltage
 * @details 1 byte. Physical [V] = Raw × 0.1 → Raw = Physical_V × 10
 *          Range: 0V (0x00) to 25.5V (0xFF).
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2006(uint8 *Data)
{
    uint16         battVoltage_mV; /* millivolts from ADC */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_BattVoltage_val(&battVoltage_mV);

    if (retVal == E_OK)
    {
        /* Convert mV to raw: raw = mV / 100 (= V × 10) */
        uint16 rawVal = battVoltage_mV / 100U;
        Data[0] = (rawVal > 0xFFU) ? 0xFFU : (uint8)rawVal;
    }
    else
    {
        Data[0] = 0xFFU;
    }

    return retVal;
}

/**
 * @brief   DID 0x2007 — Vehicle Speed
 * @details 2 bytes uint16 MSB first.
 *          Physical [km/h] = Raw × 0.01 → Raw = Physical_kmh × 100
 *          Range: 0–655.35 km/h.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2007(uint8 *Data)
{
    uint16         vehicleSpeed_kmh_x100; /* speed in 0.01 km/h units */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_VehicleSpeed_val(&vehicleSpeed_kmh_x100);

    if (retVal == E_OK)
    {
        DCM_WRITE_UINT16_BE(Data, 0U, vehicleSpeed_kmh_x100);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU);
    }

    return retVal;
}

/**
 * @brief   DID 0x2008 — Accelerator Pedal Position
 * @details 1 byte. Same encoding as throttle 0x2004 (0.4%/bit).
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2008(uint8 *Data)
{
    uint8          accelPedalPercent;
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_AccelPedalPos_val(&accelPedalPercent);

    if (retVal == E_OK)
    {
        uint16 rawVal = ((uint16)accelPedalPercent * 5U) / 2U;
        Data[0] = (rawVal > 0xFFU) ? 0xFFU : (uint8)rawVal;
    }
    else
    {
        Data[0] = 0xFFU;
    }

    return retVal;
}

/**
 * @brief   DID 0x2009 — Fuel Injection Quantity (Extended session only)
 * @details 2 bytes uint16 MSB first.
 *          Physical [mg/stroke] = Raw × 0.01 → Raw = Physical × 100
 *          Range: 0–655.35 mg/stroke.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_2009(uint8 *Data)
{
    uint16         injQty_mg_x100;  /* injection qty in 0.01 mg/stroke units */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_InjectionQty_val(&injQty_mg_x100);

    if (retVal == E_OK)
    {
        DCM_WRITE_UINT16_BE(Data, 0U, injQty_mg_x100);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU);
    }

    return retVal;
}

/**
 * @brief   DID 0x200A — Ignition Timing Advance (Extended session only)
 * @details 2 bytes sint16 MSB first.
 *          Physical [°BTDC] = Raw × 0.1 - 100
 *          Raw = (Physical + 100) / 0.1 = (Physical + 100) × 10
 *          Range: -100° to +3276.7°. Typical: -10° to +50° BTDC.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_200A(uint8 *Data)
{
    sint16         ignTimingDeg_x10;  /* timing in 0.1° units, offset applied */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_IgnTimingAdv_val(&ignTimingDeg_x10);

    if (retVal == E_OK)
    {
        /* Physical_deg = Raw × 0.1 - 100  =>  Raw = (Physical_deg + 100) × 10 */
        /* Here ignTimingDeg_x10 is already (Physical_deg × 10), so:            */
        /* Raw = ignTimingDeg_x10 + 1000 (100° offset × 10)                     */
        sint32 rawVal = (sint32)ignTimingDeg_x10 + 1000;

        if (rawVal < 0)       { rawVal = 0; }
        if (rawVal > 0xFFFF)  { rawVal = 0xFFFF; }

        DCM_WRITE_UINT16_BE(Data, 0U, (uint16)rawVal);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU);
    }

    return retVal;
}

/**
 * @brief   DID 0x200B — Lambda / O2 Sensor Value (Extended session only)
 * @details 2 bytes uint16 MSB first.
 *          Physical [lambda] = Raw × 0.0001
 *          Raw = Physical × 10000
 *          Range: 0.5λ (5000) to 2.0λ (20000).
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_200B(uint8 *Data)
{
    uint16         lambdaRaw;   /* lambda × 10000 (raw DEM unit) */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_LambdaValue_val(&lambdaRaw);

    if (retVal == E_OK)
    {
        DCM_WRITE_UINT16_BE(Data, 0U, lambdaRaw);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU);
    }

    return retVal;
}

/**
 * @brief   DID 0x200C — Injection Mode / Fuel Cut Status (Extended session)
 * @details 1 byte enum.
 *          0x00=Normal, 0x01=FuelCut, 0x02=Limp, 0x03=Cranking, 0xFF=Invalid.
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_200C(uint8 *Data)
{
    uint8          injectionMode;
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_InjectionMode_val(&injectionMode);
    Data[0] = (retVal == E_OK) ? injectionMode : DCM_INJECTION_MODE_INVALID;

    return retVal;
}

/**
 * @brief   DID 0x200D — Gear Position
 * @details 1 byte enum.
 *          0x00=Neutral, 0x01–0x08=Gear 1–8, 0x09=Reverse, 0xFF=Invalid.
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_200D(uint8 *Data)
{
    uint8          gearPosition;
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_GearPosition_val(&gearPosition);
    Data[0] = (retVal == E_OK) ? gearPosition : DCM_GEAR_INVALID;

    return retVal;
}

/**
 * @brief   DID 0x200E — Torque Request vs Actual (Extended session only)
 * @details 4 bytes: [2 bytes Requested Torque] + [2 bytes Actual Torque].
 *          Both MSB first. Physical [Nm] = Raw × 0.1. Range 0–6553.5 Nm.
 * @param   Data    [out] 4-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_200E(uint8 *Data)
{
    uint16         torqueReq_Nm_x10;  /* requested torque × 10 */
    uint16         torqueAct_Nm_x10;  /* actual torque × 10    */
    Std_ReturnType retValReq;
    Std_ReturnType retValAct;

    DCM_RETURN_IF_NULL(Data);

    retValReq = Rte_Read_TorqueReq_val(&torqueReq_Nm_x10);
    retValAct = Rte_Read_TorqueActual_val(&torqueAct_Nm_x10);

    DCM_WRITE_UINT16_BE(Data, 0U, (retValReq == E_OK) ? torqueReq_Nm_x10 : 0xFFFFU);
    DCM_WRITE_UINT16_BE(Data, 2U, (retValAct == E_OK) ? torqueAct_Nm_x10 : 0xFFFFU);

    return ((retValReq == E_OK) && (retValAct == E_OK)) ? E_OK : E_NOT_OK;
}

/**
 * @brief   DID 0x200F — Engine Run Time Since Start
 * @details 2 bytes uint16 MSB first.
 *          Physical [s] = Raw. Range: 0–65535s.
 *          Counter reset by application on each engine start event.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_200F(uint8 *Data)
{
    uint16         engRunTime_s;
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_EngRunTime_val(&engRunTime_s);

    if (retVal == E_OK)
    {
        DCM_WRITE_UINT16_BE(Data, 0U, engRunTime_s);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU);
    }

    return retVal;
}

/*============================================================================
  SECTION 3 — ECU HEALTH DIDs (0xDxxx) READ HANDLERS
============================================================================*/

/**
 * @brief   DID 0xD001 — ECU Internal Temperature
 * @details 2 bytes sint16 MSB first.
 *          Physical [°C] = Raw × 0.01. Raw = Physical × 100.
 *          Range: -327.68°C to +327.67°C.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_D001(uint8 *Data)
{
    sint16         ecuTemp_degC_x100;   /* ECU internal temp × 100 */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_EcuInternalTemp_val(&ecuTemp_degC_x100);

    if (retVal == E_OK)
    {
        /* Cast sint16 to uint16 for byte placement — two's complement preserved */
        DCM_WRITE_UINT16_BE(Data, 0U, (uint16)ecuTemp_degC_x100);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0x8000U); /* sint16 min = invalid marker */
    }

    return retVal;
}

/**
 * @brief   DID 0xD002 — Supply Voltage at ECU Pin
 * @details 2 bytes uint16 MSB first.
 *          Physical [V] = Raw × 0.001. Raw = Physical_V × 1000.
 *          Range: 0–65.535V. Typical: 9.0–16.0V.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK / E_NOT_OK
 */
Std_ReturnType Dcm_ReadData_D002(uint8 *Data)
{
    uint16         supplyVoltage_mV;   /* millivolt reading from ADC */
    Std_ReturnType retVal;

    DCM_RETURN_IF_NULL(Data);

    retVal = Rte_Read_SupplyVoltagePin_val(&supplyVoltage_mV);

    if (retVal == E_OK)
    {
        /* Raw = mV (since 1mV = 0.001V, and resolution is 0.001V/bit) */
        DCM_WRITE_UINT16_BE(Data, 0U, supplyVoltage_mV);
    }
    else
    {
        DCM_WRITE_UINT16_BE(Data, 0U, 0xFFFFU);
    }

    return retVal;
}

/**
 * @brief   DID 0xD003 — Reset Counter
 * @details 2 bytes uint16 MSB first.
 *          Cumulative reset counter since ECU production. NvM persisted.
 *          Incremented by EcuM at each startup.
 * @param   Data    [out] 2-byte response buffer
 * @return  E_OK
 */
Std_ReturnType Dcm_ReadData_D003(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);

    /* NvM RAM mirror populated by NvM_ReadAll at startup */
    Data[0] = Dcm_ResetCounterBuffer[0];
    Data[1] = Dcm_ResetCounterBuffer[1];

    return E_OK;
}

/**
 * @brief   DID 0xD004 — Last Reset Cause
 * @details 1 byte enum.
 *          0x01=Power-On-Reset, 0x02=Watchdog, 0x03=SW Reset,
 *          0x04=External, 0x05=LVD, 0xFF=Unknown.
 *          EcuM reads MCU reset status register at startup and stores in NvM.
 * @param   Data    [out] 1-byte response buffer
 * @return  E_OK
 */
Std_ReturnType Dcm_ReadData_D004(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);
    Data[0] = Dcm_ResetCauseBuffer[0];
    return E_OK;
}

/**
 * @brief   DID 0xD005 — NvM Write Cycle Counter
 * @details 4 bytes uint32 MSB first.
 *          Cumulative NvM write operations since production.
 *          Maintained by NvM job-end callback; persisted in dedicated NvM block.
 * @param   Data    [out] 4-byte response buffer
 * @return  E_OK
 */
Std_ReturnType Dcm_ReadData_D005(uint8 *Data)
{
    DCM_RETURN_IF_NULL(Data);

    Data[0] = Dcm_NvmWriteCtrBuffer[0];
    Data[1] = Dcm_NvmWriteCtrBuffer[1];
    Data[2] = Dcm_NvmWriteCtrBuffer[2];
    Data[3] = Dcm_NvmWriteCtrBuffer[3];

    return E_OK;
}

/*============================================================================
  SECTION 4 — WRITE DID HANDLERS (0x2E WriteDataByIdentifier)
============================================================================*/

/**
 * @brief   DID 0xF190 — Write VIN (Vehicle Identification Number)
 *
 * @details Accepts a 17-byte ASCII VIN from tester and stores it in NvM.
 *
 *          Pre-conditions enforced by DCM configuration (ARXML):
 *            - Active session  : Extended Diagnostic Session (0x03)
 *            - Security level  : Level 1 unlocked (seed-key completed)
 *          DCM will NOT call this function if pre-conditions are not met;
 *          it returns NRC 0x33 or 0x22 before invoking the write callout.
 *
 *          This function is responsible for:
 *            1. Validating VIN content (ISO 3779 character set)
 *            2. Storing in NvM RAM mirror
 *            3. Triggering NvM_WriteBlock for persistence
 *
 * @param   Data        [in]  17-byte VIN data from tester
 * @param   ErrorCode   [out] NRC to return on failure
 * @return  E_OK on success, E_NOT_OK with ErrorCode set on failure
 */
Std_ReturnType Dcm_WriteData_F190(
    const uint8                  *Data,
    Dcm_NegativeResponseCodeType *ErrorCode)
{
    Std_ReturnType retVal = E_OK;
    uint8          charIdx;

    /* --- Defensive NULL checks --- */
    if ((Data == NULL_PTR) || (ErrorCode == NULL_PTR))
    {
        return E_NOT_OK;
    }

    /*
     * ISO 3779 VIN character validation:
     * Valid characters: A-H, J-N, P-Z (no I, O, Q), 0-9.
     * Position 9 (check digit): 0-9 or 'X' in FMVSS 115 (US).
     * For simplicity, validate alphanumeric excluding I, O, Q.
     */
    for (charIdx = 0U; charIdx < DCM_DID_LEN_F190; charIdx++)
    {
        uint8 ch = Data[charIdx];
        boolean validChar = FALSE;

        if ((ch >= (uint8)'0') && (ch <= (uint8)'9'))
        {
            validChar = TRUE;
        }
        else if ((ch >= (uint8)'A') && (ch <= (uint8)'H'))
        {
            validChar = TRUE;
        }
        else if ((ch >= (uint8)'J') && (ch <= (uint8)'N'))
        {
            validChar = TRUE;  /* skip I */
        }
        else if ((ch >= (uint8)'P') && (ch <= (uint8)'Z'))
        {
            /* skip O (0x4F) and Q (0x51) */
            if ((ch != (uint8)'O') && (ch != (uint8)'Q'))
            {
                validChar = TRUE;
            }
        }
        else
        {
            /* invalid character */
        }

        if (validChar == FALSE)
        {
            *ErrorCode = DCM_E_REQUEST_OUT_OF_RANGE;
            retVal = E_NOT_OK;
            break;
        }
    }

    if (retVal == E_OK)
    {
        /* Copy into local RAM mirror */
        (void)memcpy(Dcm_VinBuffer, Data, DCM_DID_LEN_F190);

        /* Trigger asynchronous NvM write — persists on next NvM cycle */
        if (NvM_WriteBlock(DCM_NVM_BLOCK_VIN, Dcm_VinBuffer) != E_OK)
        {
            *ErrorCode = DCM_E_CONDITIONS_NOT_CORRECT;
            retVal     = E_NOT_OK;
        }
    }

    return retVal;
}

/*============================================================================
  SECTION 5 — INITIALISATION
  Called by application init task or EcuM startup hook before DCM starts.
============================================================================*/

/**
 * @brief   Initialise all DID handler RAM buffers from NvM.
 *
 * @details This function must be called after NvM_ReadAll() completes
 *          (i.e., in the EcuM run phase, before DCM main function starts).
 *          It copies NvM block contents into local RAM mirrors used by
 *          all async DID read handlers.
 *
 *          Non-NvM buffers (const flash symbols) require no init here.
 *
 * @return  void
 */
void Dcm_DIDHandlers_Init(void)
{
    /* NvM blocks should already be loaded by NvM_ReadAll().
     * RAM mirrors (Dcm_VinBuffer etc.) are mapped directly to NvM
     * RAM block addresses via DaVinci NvM configuration.
     * If using separate mirrors, copy here:
     *
     * (void)memcpy(Dcm_VinBuffer,
     *              NvM_VIN_Block,
     *              DCM_DID_LEN_F190);
     * etc.
     *
     * In Vector MICROSAR, NvM_Cfg.c maps the NvM RAM block pointer
     * directly to Dcm_VinBuffer — so no explicit copy is needed here
     * when NvMRamBlockDataAddress = &Dcm_VinBuffer in ARXML.
     */

    /* Safety: zero-initialise any buffer not backed by NvM at first use */
    (void)memset(Dcm_VinBuffer,          0x20U, DCM_DID_LEN_F190); /* ASCII space default */
    (void)memset(Dcm_EcuSerialBuffer,    0x20U, DCM_DID_LEN_F18C);
    (void)memset(Dcm_BootSwFpBuffer,     0x00U, DCM_DID_LEN_F183);
    (void)memset(Dcm_AppSwFpBuffer,      0x00U, DCM_DID_LEN_F184);
    (void)memset(Dcm_AppDataFpBuffer,    0x00U, DCM_DID_LEN_F185);
    (void)memset(Dcm_MfgDateBuffer,      0x00U, DCM_DID_LEN_F18B);
    (void)memset(Dcm_ProgDateBuffer,     0x00U, DCM_DID_LEN_F1A2);
    (void)memset(Dcm_ResetCounterBuffer, 0x00U, DCM_DID_LEN_D003);
    (void)memset(Dcm_ResetCauseBuffer,   DCM_RESET_CAUSE_UNKNOWN, DCM_DID_LEN_D004);
    (void)memset(Dcm_NvmWriteCtrBuffer,  0x00U, DCM_DID_LEN_D005);
}
